baseURL: "https://antrea.io/"
languageCode: "en-us"
title: "Antrea"
theme: "antrea"
outputs:
  home: ["HTML"]
  # home: ["HTML", "REDIRECTS"]
  posts: ["HTML", "RSS"]
pygmentsCodefences: true
pygmentsStyle: "pygments"
markup:
  highlight:
    anchorLineNos: false
    codeFences: true
    guessSyntax: false
    hl_Lines: ""
    lineAnchors: ""
    lineNoStart: 1
    lineNos: false
    lineNumbersInTable: true
    noClasses: true
    style: native
    tabWidth: 4
  goldmark:
    renderer:
      unsafe: true
params:
  twitter_url: "https://twitter.com/projectantrea"
  github_url: "https://github.com/antrea-io/antrea"
  slack_url: "https://kubernetes.slack.com/archives/CR2J23M0X"
  github_website_url: "https://github.com/antrea-io/website"
  rss_url: "/blog/feed.xml"
  use_advanced_docs: true
  docs_right_sidebar: false
  docs_search: false
  docs_search_index_name: index_name
  docs_search_api_key: api_key
  docs_versioning: true
  docs_latest: v1.11.0
  docs_versions:
    - main
    - v1.11.0
    - v1.10.0
    - v1.9.0
    - v1.8.0
    - v1.7.3
    - v1.7.2
    - v1.7.1
    - v1.7.0
    - v1.6.1
    - v1.6.0
    - v1.5.3
    - v1.5.2
    - v1.5.1
    - v1.5.0
    - v1.4.0
    - v1.3.0
    - v1.2.3
    - v1.2.2
    - v1.2.1
    - v1.2.0
mediaTypes:
  "text/netlify":
    delimiter: ""
outputFormats:
  # this would override our default one?
  # REDIRECTS:
  #   mediaType: "text/netlify"
  #   baseName: "_redirects"
  RSS:
    mediatype: "application/rss"
    baseName: "feed"
ignoreFiles:
  # Without this we end up with 2 api-reference files under public/:
  # api-reference.html (original) and api-reference/index.html (generated by
  # Hugo). Only the latter one is needed, and for some reason when using Netlify
  # to build the website the former one is "picked", leading to incorrect
  # formatting for that webpage. Surprisingly, I cannot reproduce the issue when
  # building locally.
  - api-reference\.html
